kind: Deployment
apiVersion: apps/v1
metadata:
  name: jwt-auth-service
  namespace: naeemark
  selfLink: /apis/apps/v1/namespaces/naeemark/deployments/jwt-auth-service
  uid: 7bda27d8-d1e0-41bd-9ac6-a2de21716abc
  resourceVersion: "722168881"
  generation: 1
  creationTimestamp: 2020-08-21T06:18:12Z
  labels:
    app: jwt-auth-service
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-auth-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jwt-auth-service
    spec:
      containers:
        - name: api
          image: naeemark/aa-jwt-auth-service
          ports:
            - name: http-ports
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: "True"
      lastUpdateTime: 2020-08-21T06:18:12Z
      lastTransitionTime: 2020-08-21T06:18:12Z
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: "True"
      lastUpdateTime: 2020-08-21T06:18:14Z
      lastTransitionTime: 2020-08-21T06:18:12Z
      reason: NewReplicaSetAvailable
      message: ReplicaSet "jwt-auth-service-78c79f8d77" has successfully progressed.
